#!/usr/bin/env python


from munin.redis_db_base import MuninRedisDBPlugin


class MuninRedisDB3Plugin(MuninRedisDBPlugin):
    db_name = "db3"


if __name__ == "__main__":
    MuninRedisDB3Plugin().run()
